SELECT productid
    , businessentityid
    , averageleadtime
    , standardprice
    , lastreceiptcost
    , lastreceiptdate
    , minorderqty
    , maxorderqty
    , onorderqty
    , unitmeasurecode
    , modifieddate
from "advworks_famd"."purchasing"."productvendor"
