version: 2

snapshots:
  - name: sp_employee
    description: "A snapshot of the stg_employee model, to keep track of changes to that table"
    columns:
      - name: employee_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - unique
          - not_null

  - name: sp_product
    description: "A snapshot of the stg_product model, to keep track of changes to that table"
    columns:
      - name: product_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null
          - unique

  - name: sp_productvendor
    description: "A snapshot of the stg_productvendor model, to keep track of changes to that table"
    columns:
      - name: product_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null

  - name: sp_fact_pmanagement
    description: "A snapshot of the stg_productvendor model, to keep track of changes to that table"
    columns:
      - name: purchaseorder_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null

          