version: 2

snapshots:

  - name: sp_eemployee
    description: "A snapshot of the stg_employee model, to keep track of changes to that table"
    columns:
      - name: employee_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - unique
          - not_null

  - name: sp_pproduct
    description: "A snapshot of the stg_product model, to keep track of changes to that table"
    columns:
      - name: purchaseorder_id
        description: "A surrogate key created by dbt. It is the primary key of this table"

  - name: sp_pperson
    description: "A snapshot of the stg_productvendor model, to keep track of changes to that table"
    columns:
      - name: employee_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null
          - unique

  - name: sp_purchaseorderdetail
    description: "A snapshot of the stg_productvendor model, to keep track of changes to that table"
    columns:
      - name: purchaseorder_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null

  - name: sp_shipmethod
    description: "A snapshot of the stg_productvendor model, to keep track of changes to that table"
    columns:
      - name: shipmethod_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null
          - unique

  - name: sp_purchaseorderheader
    description: "A snapshot of the stg_productvendor model, to keep track of changes to that table"
    columns:
      - name: purchaseorder_id
        description: "A surrogate key created by dbt. It is the primary key of this table"
        tests:
          - not_null
          - unique

