version: 2

sources:
  - name: humanresources
    schema: humanresources
    tables:
      - name: employee
      - name: department
      - name: shift
      - name: employeedepartmenthistory
      - name: employeepayhistory
      - name: jobcandidate

  - name: person
    schema: person
    tables:
      - name: person
      - name: address
      - name: addresstype
      - name: businessentity
      - name: businessentityaddress
      - name: businessentitycontact
      - name: contacttype
      - name: emailaddress
      - name: password
      - name: personphone
      - name: phonenumbertype
      - name: stateprovince
      - name: countryregion

  - name: production
    schema: production
    tables:
      - name: product

  - name: sales
    schema: sales
    tables:
      - name: creditcard
      - name: customer
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: stateprovince
      - name: store

  - name: purchasing
    schema: purchasing
    tables:
      - name: productvendor
      - name: purchasing
      - name: purchaseorderdetail
      - name: purchaseorderheader
      - name: shipmethod
      - name: vendor

models:
  - name: stg_employee
    columns:
      - name: employee_id
        description: "A unique identifier for the employee, to join stg_person.businessentity_id"
        tests:
          - unique
          - not_null

  - name: stg_product
    columns:
      - name: product_id
        description: "A identifier for the pkey, to join stg_salesorderdetails.product_id"

  - name: stg_productvendor
    columns:
      - name: product_id
        description: "Primary key. Foreign key to stg_product.product_id"
        tests:
          - not_null

  - name: stg_purchaseorderdetail
    columns:
      - name: purchaseorderid
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - not_null

  - name: stg_purchaseorderheader
    columns:
      - name: purchaseorderid
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - not_null

  - name: stg_shipmethod
    columns:
      - name: businessentityid
        description: "Primary key. Foreign key to stg_customer.store_id"

  - name: stg_vendor
    columns:
      - name: shipmethodid
        description: "Primary key. Foreign key to stg_customer.store_id"

  - name: dim_header
    columns:
      - name: purchaseorderid
        description: "Surrogate key"
        tests:
          - not_null
