version: 2

sources:
  - name: person
    schema: person
    tables:
      - name: person

  - name: production
    schema: production
    tables:
      - name: product


  - name: purchasing
    schema: purchasing
    tables:
      - name: productvendor
      - name: purchaseorderdetail
      - name: purchaseorderheader
      - name: shipmethod
      - name: vendor

models:
  - name: stg_pperson
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null

  - name: stg_pproduct
    columns:
      - name: product_id
        description: "A identifier for the pkey, to join stg_salesorderdetails.product_id"

  - name: stg_productvendor
    columns:
      - name: product_id
        description: "Primary key. Foreign key to stg_product.product_id"
        tests:
          - not_null

  - name: stg_purchaseorderdetail
    columns:
      - name: purchaseorderid
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - not_null

  - name: stg_purchaseorderheader
    columns:
      - name: purchaseorderid
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - not_null

  - name: stg_shipmethod
    columns:
      - name: businessentityid
        description: "Primary key. Foreign key to stg_customer.store_id"

  - name: stg_vendor
    columns:
      - name: shipmethodid
        description: "Primary key. Foreign key to stg_customer.store_id"

  - name: dim_header
    columns:
      - name: purchaseorderid
        description: "Surrogate key"
        tests:
          - not_null

  - name: dim_data
    columns:
      - name: date
        description: "Surrogate key"
        tests:
          - not_null

  - name: dim_eemployee
    columns:
      - name: employee_id
        description: "Surrogate key"
        tests:
          - not_null

  - name: dim_pproducts
    columns:
      - name: purchaseorderid
        description: "Surrogate key"
        tests:
          - not_null

  - name: fact_pmanagement
    columns:
      - name: sk_product_id
        description: "Surrogate key"
        tests:
          - not_null
