version: 2

sources:
  - name: humanresources
    schema: humanresources
    tables:
      - name: employee
      - name: department
      - name: shift
      - name: employeedepartmenthistory
      - name: employeepayhistory
      - name: jobcandidate


  - name: person
    schema: person
    tables:
      - name: person
      - name: address
      - name: addresstype
      - name: businessentity
      - name: businessentityaddress
      - name: businessentitycontact
      - name: contacttype
      - name: emailaddress
      - name: password
      - name: personphone
      - name: phonenumbertype
      - name: stateprovince
      - name: countryregion

  - name: production
    schema: production
    tables:
      - name: product

  - name: sales
    schema: sales
    tables:
      - name: creditcard
      - name: customer
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: stateprovince
      - name: store


  - name: purchasing
    schema: purchasing
    tables:
      - name: productvendor




models:
  - name: stg_employee
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null


  - name: stg_address
    columns:
      - name: address_id
        description: "A unique identifier for the address"
        tests:
          - not_null
          - unique

  - name: stg_countryregion
    columns:
      - name: countryregioncode
        description: "A unique identifier for the country"
        tests:
          - unique
          - not_null

  - name: stg_creditcard
    columns:
      - name: creditcard_id
        description: "A unique identifier for the creditcard"
        tests:
          - unique
          - not_null

  - name: stg_productvendor
    columns:
      - name: productid
        description: "A unique identifier for the productvendor"
        tests:
          - not_null
