version: 2

sources:
  - name: humanresources
    schema: humanresources
    tables:
     - name: employee
     - name: department
     - name: shift
  - name: person
    schema: person
    tables:
      - name: person

models:
  - name: stg_employee
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null

