version: 2

sources:
  - name: person
    schema: person
    tables:
      - name: person

  - name: production
    schema: production
    tables:
      - name: product


  - name: purchasing
    schema: purchasing
    tables:
      - name: productvendor
      - name: purchaseorderdetail
      - name: purchaseorderheader
      - name: shipmethod

models:
  - name: stg_pperson
    columns:
      - name: employee_id
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null

  - name: stg_pproduct
    columns:
      - name: product_id
        description: "A identifier for the pkey, to join stg_salesorderdetails.product_id"
        tests:
          - unique
          - not_null

  - name: stg_productvendor
    columns:
      - name: product_id
        description: "Primary key. Foreign key to stg_product.product_id"
        tests:
          - unique
          - not_null

  - name: stg_purchaseorderdetail
    columns:
      - name: purchaseorderdetail_id
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - unique
          - not_null

  - name: stg_purchaseorderheader
    columns:
      - name: purchaseorder_id
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - unique
          - not_null

  - name: stg_shipmethod
    columns:
      - name: shipmethod_id
        description: "Primary key. Foreign key to stg_customer.store_id"
        tests:
          - unique
          - not_null
